# This is a generated file. Not intended for manual editing.
services:
  integrity-service:
    build:
      context: "/Users/macuser/Documents/projects/temp/fin-tech-app-payze"
      dockerfile: "IntegrityService/App/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/App.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "integrity-service:dev"
    ports: []
    volumes:
    - "/Users/macuser/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/macuser/Documents/projects/temp/fin-tech-app-payze/IntegrityService/App:/app:rw"
    - "/Users/macuser/Documents/projects/temp/fin-tech-app-payze:/src:rw"
    working_dir: "/app"
  order-service:
    build:
      context: "/Users/macuser/Documents/projects/temp/fin-tech-app-payze"
      dockerfile: "App/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/App.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "order-service:dev"
    ports: []
    volumes:
    - "/Users/macuser/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/macuser/Documents/projects/temp/fin-tech-app-payze/App:/app:rw"
    - "/Users/macuser/Documents/projects/temp/fin-tech-app-payze:/src:rw"
    working_dir: "/app"
  payment-app:
    build:
      context: "/Users/macuser/Documents/projects/temp/fin-tech-app-payze"
      dockerfile: "Payment.App/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Payment.App.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "payment-app:dev"
    ports: []
    volumes:
    - "/Users/macuser/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/macuser/Documents/projects/temp/fin-tech-app-payze/Payment.App:/app:rw"
    - "/Users/macuser/Documents/projects/temp/fin-tech-app-payze:/src:rw"
    working_dir: "/app"
