# This is a generated file. Not intended for manual editing.
services:
  integrity-service:
    build:
      context: "/Users/macuser/Documents/projects/payze-technical-interview/fin-tech-app"
      dockerfile: "IntegrityService/App/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "integrity-service:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "/Users/macuser/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/macuser/Documents/projects/payze-technical-interview/fin-tech-app/IntegrityService/App:/app:rw"
    - "/Users/macuser/Documents/projects/payze-technical-interview/fin-tech-app:/src:rw"
    - "/Users/macuser/.local/share/JetBrains/RiderRemoteDebugger/2024.1.3/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/macuser/Library/Logs/JetBrains/Rider2024.1/DebuggerWorker/JetBrains.Debugger.Worker.2024_6_25_10_58_37:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  order-service:
    build:
      context: "/Users/macuser/Documents/projects/payze-technical-interview/fin-tech-app"
      dockerfile: "App/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "order-service:dev"
    ports:
    - "127.0.0.1:57004:57100"
    - "127.0.0.1:57204:57300"
    volumes:
    - "/Users/macuser/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/macuser/Documents/projects/payze-technical-interview/fin-tech-app/App:/app:rw"
    - "/Users/macuser/Documents/projects/payze-technical-interview/fin-tech-app:/src:rw"
    - "/Users/macuser/.local/share/JetBrains/RiderRemoteDebugger/2024.1.3/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/macuser/Library/Logs/JetBrains/Rider2024.1/DebuggerWorker/JetBrains.Debugger.Worker.2024_6_25_10_58_37:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  payment-app:
    build:
      context: "/Users/macuser/Documents/projects/payze-technical-interview/fin-tech-app"
      dockerfile: "Payment.App/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "payment-app:dev"
    ports:
    - "127.0.0.1:57005:57100"
    - "127.0.0.1:57205:57300"
    volumes:
    - "/Users/macuser/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/macuser/Documents/projects/payze-technical-interview/fin-tech-app/Payment.App:/app:rw"
    - "/Users/macuser/Documents/projects/payze-technical-interview/fin-tech-app:/src:rw"
    - "/Users/macuser/.local/share/JetBrains/RiderRemoteDebugger/2024.1.3/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/macuser/Library/Logs/JetBrains/Rider2024.1/DebuggerWorker/JetBrains.Debugger.Worker.2024_6_25_10_58_37:/var/opt/rider-debugger:rw"
    working_dir: "/app"
